#!/bin/bash
echo "Applying bosh-dev patch to bosh_warden_cpi"

sudo sed -i 's|      return \[bind_mount, ephemeral_mount\]| \
dev_mount = Warden::Protocol::CreateRequest::BindMount.new \
dev_mount.src_path = "bosh-dev" \
dev_mount.dst_path = "/bosh-dev" \
dev_mount.mode = Warden::Protocol::CreateRequest::BindMount::Mode::RW \
return [bind_mount, ephemeral_mount, dev_mount]|g' \
/opt/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_warden_cpi-1.5.0.pre.66/lib/cloud/warden/cloud.rb

echo "Restarting warden"
sudo kill $(ps aux | grep "[r]ake warden:start" | awk '{print $2}')
